name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run lint
        run: flake8 app.py
  build:
    needs: [test,lint]
    steps:
      - name: Notify
        run: echo "Da test va lint xong, gio toi build"

      - name: Clean first
        run: sudo apt-get remove docker.io docker-compose docker-compose-v2 podman-docker containerd runc

      - name: Setup repository
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl
      
      - name: Install docker engine
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Build container
        run: docker build -t my-python-app .
        
      - name: Run container
        run: docker run --rm my-python-app
